Repository jungle-royale/jungle-royale-game-client, pull requests merged in 2025-01, with the labels that each got.

#32 feat: 누르고 있으면 연사로 나가도록 처리
  Assets/Proto/message.proto
  Assets/Scripts/Controller/Tile/Tile.cs
  Assets/Scripts/Controller/Tile/TileController.cs
  Assets/Scripts/Manager/GameManager.cs
  Assets/Scripts/Manager/InputManager.cs
  Assets/Scripts/Proto/Message.cs
Labels: 기능

#42 Issue41/heatbullet getitem playerdead
  Assets/Proto/message.proto
  Assets/Scripts/Manager/ChangingState.meta
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs.meta
  Assets/Scripts/Manager/ChangingState/GetItemState.cs
  Assets/Scripts/Manager/ChangingState/GetItemState.cs.meta
  Assets/Scripts/Manager/ChangingState/HeatBulletState.cs
  Assets/Scripts/Manager/ChangingState/HeatBulletState.cs.meta
  Assets/Scripts/Manager/ChangingState/PlayerDeadState.cs
  Assets/Scripts/Manager/ChangingState/PlayerDeadState.cs.meta
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/Tile/TileManager.cs
  Assets/Scripts/Proto/Message.cs
Labels: 기능

#44 chore: 빌드 캐시 모드 추가, 모바일 로딩 화면 문구 추가
  Assets/Editor/WebGLBuildScript.cs
  Assets/WebGLTemplates/CustomTemplate/index.html
Labels: 기능

#55 fix: Aim 조이스틱 손떼었을 때 방향 고정
  Assets/Resources.meta
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/Input/InputAdapter.cs
Labels: 버그, 기능

#57 feat: 대기화면에서 총알 충돌처리 구현
  Assets/DownloadedAssets/LowPolyWater_Pack/Plane Meshes/Ocean50x50W750H750.asset.meta
  Assets/Proto/message.proto
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Proto/Message.cs
Labels: 기능

#66 Issue58/animation
  Assets/Proto/message.proto
  Assets/Resources/Animations.meta
  Assets/Resources/Animations/Player.controller
  Assets/Resources/Animations/Player.controller.meta
  Assets/Resources/Animations/PlayerAnimation.controller
  Assets/Resources/Animations/PlayerAnimation.controller.meta
  Assets/Resources/Animations/SnowManIdle.anim
  Assets/Resources/Animations/SnowManIdle.anim.meta
  Assets/Resources/Animations/SnowManMovement.anim
  Assets/Resources/Animations/SnowManMovement.anim.meta
  Assets/Resources/Animations/SnowmanAnimationController.controller
  Assets/Resources/Animations/SnowmanAnimationController.controller.meta
  Assets/Resources/Prefabs/Characters/CurrentPlayer.prefab
  Assets/Resources/Prefabs/Characters/OtherPlayer.prefab
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs
  Assets/Scripts/Manager/ChangingState/DoDashState.cs
  Assets/Scripts/Manager/ChangingState/DoDashState.cs.meta
  Assets/Scripts/Manager/ChangingState/HeatBulletState.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/GameState/GameStateManager.cs
  Assets/Scripts/Manager/Input/InputManager.cs
  Assets/Scripts/Manager/Player/Player.cs
  Assets/Scripts/Manager/Player/PlayerManager.cs
  Assets/Scripts/Manager/Tile/Tile.cs
  Assets/Scripts/Manager/Tile/TileManager.cs
  Assets/Scripts/Proto/Message.cs
  server/server.js
Labels: 기능

#68 feat: HealEffect 구현, 이펙트 및 HPbar Y축 고정, protobuf 업데이트, Timer UI 업데이트
  Assets/DownloadedAssets/LowPolyWater_Pack/Plane Meshes/Ocean50x50W750H750.asset
  Assets/Proto/message.proto
  Assets/Resources/Prefabs/Characters/CurrentPlayer.prefab
  Assets/Resources/Prefabs/Characters/OtherPlayer.prefab
  Assets/Resources/Prefabs/Effects/HealEffect.prefab
  Assets/Resources/Prefabs/UIs/MainCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Common/FollowParentXZ.cs
  Assets/Scripts/Common/FollowParentXZ.cs.meta
  Assets/Scripts/HUD/BillBoard.cs
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/GameState/GameStateManager.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIEventType.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
  Assets/Scripts/Manager/Input/InputManager.cs
  Assets/Scripts/Proto/Message.cs
  ProjectSettings/TagManager.asset
Labels: 버그, 기능

#74 feat: 대시, 걷기 소리 주체 수정
  Assets/Resources/Animations/SnowManMovement.anim
  Assets/Resources/Prefabs/Characters/CurrentPlayer.prefab
  Assets/Resources/Prefabs/Characters/OtherPlayer.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Audio/AudioManager.cs
  Assets/Scripts/Manager/Bullet/BulletManager.cs
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/Input/InputManager.cs
  Assets/Scripts/Manager/Player/MoveEvent.cs
  Assets/Scripts/Manager/Player/MoveEvent.cs.meta
  Assets/Scripts/Manager/Player/PlayerManager.cs
Labels: 기능

#76 feat: HitNormal, HitFire, HitStone 이펙트 추가
  Assets/DownloadedAssets/Hovl Studio/Magic effects pack/Materials/Heart.mat
  Assets/Resources/Prefabs/Characters/CurrentPlayer.prefab
  Assets/Resources/Prefabs/Effects/HitFire.prefab
  Assets/Resources/Prefabs/Effects/HitFire.prefab.meta
  Assets/Resources/Prefabs/Effects/HitNormal.prefab
  Assets/Resources/Prefabs/Effects/HitNormal.prefab.meta
  Assets/Resources/Prefabs/Effects/HitSnow.prefab
  Assets/Resources/Prefabs/Effects/HitSnow.prefab.meta
  Assets/Resources/Prefabs/Effects/HitStone.prefab
  Assets/Resources/Prefabs/Effects/HitStone.prefab.meta
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/Bullet/BulletManager.cs
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs
  Assets/Scripts/Manager/ChangingState/HeatBulletState.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
  ProjectSettings/ProjectSettings.asset
Labels: 기능

#79 feat: 소켓 연결 안되었을 때 리다이렉트 처리
  Assets/Scripts/Common/javascript/RedirectHandler.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
Labels: 기능

#83 feat: 대기방 제거
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/GameState/GameStateManager.cs
  Assets/Scripts/Manager/Player/PlayerManager.cs
  Assets/Scripts/Manager/Tile/TileManager.cs
Labels: 기능

#85 Issue84/reconnect
  Assets/Proto/message.proto
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/Player/PlayerManager.cs
  Assets/Scripts/Proto/Message.cs
Labels: 기능

#88 fix: 리다이렉트 되는 문제 수정
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/Input/InputButtonEventType.cs
  Assets/Scripts/Manager/Input/InputManager.cs
Labels: 버그

#89 fix: 뒤로가기 막기 코드 제거
  Assets/WebGLTemplates/CustomTemplate/index.html
Labels: 기능

#91 fix: 리커넥션 시 로딩 제거
  Assets/Scripts/Manager/GameNetworkManager.cs
Labels: 버그

#99 feat: ping 추가
  Assets/Scripts/Manager/GameNetworkManager.cs
Labels: 기능

#101 Issue95 웹 프론트 빌드 다운로드 속도 개선
  ProjectSettings/ProjectSettings.asset
  server/package-lock.json
  server/package.json
  server/server.js
Labels: 버그, 기능

#102 fix: index.html 콘텐츠 타입 명시
  server/server.js
Labels: 버그

#108 Issue106 사용성 개선, 버그 수정
  Assets/Resources/Animations/SnowManFallingAnimation.anim
  Assets/Resources/Animations/SnowManMovement.anim
  Assets/Resources/Animations/SnowManWin.anim
  Assets/Resources/Animations/SnowManWin.anim.meta
  Assets/Resources/Animations/SnowmanAnimationController.controller
  Assets/Resources/Animations/SnowmanDeadAnimation.anim
  Assets/Resources/Animations/SnowmanDeadAnimation.anim.meta
  Assets/Resources/Animations/TileFallingAnimation.anim
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/Camera/Tile00.csv
  Assets/Scripts/Manager/ChangingState/ChangingStateManager.cs
  Assets/Scripts/Manager/ClientManager.cs
  Assets/Scripts/Manager/GameState/GameStateManager.cs
  Assets/Scripts/Manager/Input/InputAdapter.cs
  Assets/Scripts/Manager/Input/InputManager.cs
  Assets/Scripts/Manager/Player/PlayerAnimationEvent.cs
  Assets/Scripts/Manager/Tile/TileManager.cs
Labels: 버그, 기능

#110 fix: 카메라 흔들 때 깜빡이는 문제 수정
  Assets/Scripts/Manager/Camera/CameraManager.cs
Labels: 버그

#112 feat: 지진 소리 추가
  Assets/Resources/Animations/SnowmanDeadAnimation.anim
  Assets/Resources/Audio/SFX/DestroyGround.wav
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/Player/PlayerAnimationEvent.cs
Labels: 기능

#117 Issue113
  Assets/Proto/message.proto
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/Player/Player.cs
  Assets/Scripts/Manager/Player/PlayerManager.cs
  Assets/Scripts/Proto/Message.cs
Labels: 기능

#122 feat: 핑 호출 방식 변경, 에러 화면 추가
  Assets/Scripts/Manager/GameNetworkManager.cs
Labels: 기능

#126 fix: 플레이어 투명인간 수정, BulletBar 버그 수정, GUI 겹침 수정, ClientManager MagicTyp…
  Assets/Resources/Prefabs/Characters/Player.prefab
  Assets/Resources/Prefabs/UIs/BulletGageBar.prefab
  Assets/Resources/Prefabs/UIs/GameEndCanvas.prefab
  Assets/Resources/Prefabs/UIs/GameOverCanvas.prefab
  Assets/Resources/Prefabs/UIs/GameWinCanvas.prefab
  Assets/Resources/Prefabs/UIs/PlayerCanvas.prefab
  Assets/Resources/Prefabs/UIs/StateContainer.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/ClientManager.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
  Assets/Scripts/Manager/InGameGUI/QRButton.cs
  Assets/Scripts/Manager/Magic/MagicType.cs
  Assets/Scripts/Manager/Player/PlayerManager.cs
  ProjectSettings/TagManager.asset
Labels: 기능

#128 fix: 승천 문제 해결
  Assets/Scripts/Manager/Player/PlayerManager.cs
Labels: 버그

#130 feat: 관전 자유 시점 추가
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/InGameGUI/WatchGameButton.cs
  Assets/Scripts/Manager/Input/InputManager.cs
Labels: 버그, 기능

#143 feat: Guide Button, DescriptioinCanvas 구현, QRCode 위치 수정
  Assets/Fonts/NotoSansKR-Bold SDF.mat
  Assets/Fonts/NotoSansKR-Bold SDF.mat.meta
  Assets/Fonts/NotoSansKR-Bold SDF_BlackOutline.mat
  Assets/Fonts/NotoSansKR-Bold SDF_BlackOutline.mat.meta
  Assets/Fonts/NotoSansKR-Bold SDF_Shadow.mat
  Assets/Fonts/NotoSansKR-Bold SDF_Shadow.mat.meta
  Assets/Resources/Prefabs/UIs/DescriptionCanvas.prefab
  Assets/Resources/Prefabs/UIs/DescriptionCanvas.prefab.meta
  Assets/Resources/Prefabs/UIs/ItemInfoCanvas.prefab
  Assets/Resources/Prefabs/UIs/ItemInfoCanvas.prefab.meta
  Assets/Resources/Prefabs/UIs/MainCanvas.prefab
  Assets/Resources/Prefabs/UIs/WaitingRoomCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/Bullet/BulletManager.cs
  Assets/Scripts/Manager/GameNetworkManager.cs
  Assets/Scripts/Manager/InGameGUI/GuideToggleButtion.cs
  Assets/Scripts/Manager/InGameGUI/GuideToggleButtion.cs.meta
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
  Assets/Scripts/Manager/InGameGUI/QRButton.cs
  Assets/Scripts/Manager/Input/InputManager.cs
Labels: 기능

#144 fix: Scene 저장, Descriptioin Canvas 투명도 수정, Guide 버튼 누르면 다른 캔버스도 비활성화 …
  Assets/Resources/Prefabs/UIs/DescriptionCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/InGameGUI/GuideToggleButtion.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIEventType.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
Labels: 기능

#152 feat: 데미지 받을 때 화면 붉게 깜빡이도록 구현
  Assets/Resources/Prefabs/Characters/Player.prefab
  Assets/Resources/Prefabs/Effects/DamageEffectCanvas.prefab
  Assets/Resources/Prefabs/Effects/DamageEffectCanvas.prefab.meta
  Assets/Resources/Prefabs/UIs/PlayerCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/HUD/DamageEffect.cs
  Assets/Scripts/HUD/DamageEffect.cs.meta
  Assets/Scripts/HUD/HealthBar.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
Labels: 기능

#160 feat: 파도 변경, 아이템 가이드 위치 변경, ItemInfoCanvas 레이아웃 조정
  Assets/DownloadedAssets/Texture/Simple Water Shader.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Demo.unity
  Assets/DownloadedAssets/Texture/Simple Water Shader/Demo.unity.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Icons.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Icons/Help_Icon.png
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Icons/Help_Icon.png.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Icons/Water Shader icon.PNG
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Icons/Water Shader icon.PNG.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Readme.asset
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Readme.asset.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts/Editor.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts/Editor/ReadmeEditor.cs
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts/Editor/ReadmeEditor.cs.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts/Readme.cs
  Assets/DownloadedAssets/Texture/Simple Water Shader/Info/Scripts/Readme.cs.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Prefabs.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Prefabs/WaterBlock_50m.prefab
  Assets/DownloadedAssets/Texture/Simple Water Shader/Prefabs/WaterBlock_50m.prefab.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Prefabs/WaterReflectionCamera.prefab
  Assets/DownloadedAssets/Texture/Simple Water Shader/Prefabs/WaterReflectionCamera.prefab.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterBlock_50m.mesh
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterBlock_50m.mesh.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterReflection.cs
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterReflection.cs.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterReflection.renderTexture
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterReflection.renderTexture.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterShader.shadergraph
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterShader.shadergraph.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterSurface_atlas.tif
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterSurface_atlas.tif.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterSurface_single.tif
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/WaterSurface_single.tif.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_01.mat
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_01.mat.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_02.mat
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_02.mat.meta
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_03.mat
  Assets/DownloadedAssets/Texture/Simple Water Shader/Resources/Water_mat_03.mat.meta
  Assets/Resources/Prefabs/Characters/Player.prefab
  Assets/Resources/Prefabs/UIs/ItemInfoCanvas.prefab
  Assets/Resources/Prefabs/UIs/PlayerCanvas.prefab
  Assets/Resources/Prefabs/UIs/WatchModeCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Common/ItemTrigger.cs
  Assets/Settings/URP-HighFidelity.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Anton SDF.asset
  Assets/TextMesh Pro/Examples & Extras/Resources/Fonts & Materials/Roboto-Bold SDF.asset
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: 기능

#163 fix: 보기 전환 버튼 버그 수정
  Assets/Materials/CrackedGround.mat
  Assets/Resources/Prefabs/UIs/MainCanvas.prefab
  Assets/Resources/Prefabs/UIs/WatchModeCanvas.prefab
  Assets/Scenes/InGameScene.unity
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
  Assets/Scripts/Manager/InGameGUI/NextButton.cs
  Assets/Scripts/Manager/Tile/GroundCrack.cs
  Assets/Scripts/Manager/Tile/GroundCrack.cs.meta
Labels: 기능

#165 fix: 관전, 보기 전환 버그 수정
  Assets/Resources/Prefabs/UIs/GameEndCanvas.prefab
  Assets/Resources/Prefabs/UIs/GameOverCanvas.prefab
  Assets/Resources/Prefabs/UIs/GameWinCanvas.prefab
  Assets/Resources/Prefabs/UIs/MainCanvas.prefab
  Assets/Scripts/Manager/Camera/CameraManager.cs
  Assets/Scripts/Manager/InGameGUI/InGameGUIManager.cs
Labels: 버그
